# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui/ui_confirm_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(430, 199)
        Dialog.setStyleSheet("* {\n"
"    font: 12pt \"Lucida Casual\";\n"
"}\n"
"#centralWidget {\n"
"    background-color: #202020;\n"
"    border: 1px solid rgb(44, 49, 58);\n"
"    border-radius: 7px;\n"
"    border: 2px solid #4a4a4a;\n"
"}\n"
"\n"
"QLabel {\n"
"    color: #ffffff;\n"
"    padding: 10px 10px;\n"
"}\n"
"\n"
"#labelTitle {\n"
"    font: 18pt \"Lucida Casual\";\n"
"}\n"
"\n"
"#line, #line_2, #line_3 {\n"
"    background: #4a4a4a;\n"
"}\n"
"\n"
"QPushButton {\n"
"    border-bottom-left-radius: 7px;\n"
"    border: none;\n"
"    background-color: transparent;\n"
"    color: #ffffff;\n"
"    /* border: 1px solid #575757;*/\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #424242;\n"
"}\n"
"\n"
"#buttonConfirm {\n"
"    background-color: transparent;\n"
"    color: #f77861;\n"
"    border-bottom-left-radius: 0px;\n"
"}\n"
"\n"
"#buttonConfirm:hover {\n"
"    background-color: #3b3230;\n"
"}")
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.centralWidget = QtWidgets.QWidget(Dialog)
        self.centralWidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.centralWidget.setStyleSheet("")
        self.centralWidget.setObjectName("centralWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralWidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.labelTitle = QtWidgets.QLabel(self.centralWidget)
        font = QtGui.QFont()
        font.setFamily("Lucida Casual")
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.labelTitle.setFont(font)
        self.labelTitle.setAlignment(QtCore.Qt.AlignCenter)
        self.labelTitle.setObjectName("labelTitle")
        self.verticalLayout_2.addWidget(self.labelTitle)
        self.line_3 = QtWidgets.QFrame(self.centralWidget)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.verticalLayout_2.addWidget(self.line_3)
        self.labelMessage = QtWidgets.QLabel(self.centralWidget)
        self.labelMessage.setMinimumSize(QtCore.QSize(0, 80))
        font = QtGui.QFont()
        font.setFamily("Lucida Casual")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.labelMessage.setFont(font)
        self.labelMessage.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.labelMessage.setObjectName("labelMessage")
        self.verticalLayout_2.addWidget(self.labelMessage)
        self.line_2 = QtWidgets.QFrame(self.centralWidget)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout_2.addWidget(self.line_2)
        self.frame = QtWidgets.QFrame(self.centralWidget)
        self.frame.setMinimumSize(QtCore.QSize(0, 0))
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setContentsMargins(2, 0, 2, 2)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.buttonCancel = QtWidgets.QPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonCancel.sizePolicy().hasHeightForWidth())
        self.buttonCancel.setSizePolicy(sizePolicy)
        self.buttonCancel.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Lucida Casual")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.buttonCancel.setFont(font)
        self.buttonCancel.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.buttonCancel.setObjectName("buttonCancel")
        self.horizontalLayout.addWidget(self.buttonCancel)
        self.line = QtWidgets.QFrame(self.frame)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout.addWidget(self.line)
        self.buttonConfirm = QtWidgets.QPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonConfirm.sizePolicy().hasHeightForWidth())
        self.buttonConfirm.setSizePolicy(sizePolicy)
        self.buttonConfirm.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Lucida Casual")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.buttonConfirm.setFont(font)
        self.buttonConfirm.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.buttonConfirm.setIconSize(QtCore.QSize(20, 20))
        self.buttonConfirm.setObjectName("buttonConfirm")
        self.horizontalLayout.addWidget(self.buttonConfirm)
        self.verticalLayout_2.addWidget(self.frame)
        self.verticalLayout.addWidget(self.centralWidget)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.labelTitle.setText(_translate("Dialog", "Confirm"))
        self.labelMessage.setText(_translate("Dialog", "Are you sure to delete item"))
        self.buttonCancel.setText(_translate("Dialog", "Cancel"))
        self.buttonConfirm.setText(_translate("Dialog", "Supprimer"))
