# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\gui\ui_trizClients.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1125, 542)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.frame = QtWidgets.QFrame(Dialog)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.editSearchTrizClient = QtWidgets.QLineEdit(self.frame)
        self.editSearchTrizClient.setObjectName("editSearchTrizClient")
        self.horizontalLayout.addWidget(self.editSearchTrizClient)
        self.buttonSearchTrizClient = QtWidgets.QPushButton(self.frame)
        self.buttonSearchTrizClient.setObjectName("buttonSearchTrizClient")
        self.horizontalLayout.addWidget(self.buttonSearchTrizClient)
        self.verticalLayout.addWidget(self.frame)
        self.tableWidgetTrizClients = QtWidgets.QTableWidget(Dialog)
        self.tableWidgetTrizClients.setEditTriggers(QtWidgets.QAbstractItemView.DoubleClicked)
        self.tableWidgetTrizClients.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableWidgetTrizClients.setShowGrid(False)
        self.tableWidgetTrizClients.setObjectName("tableWidgetTrizClients")
        self.tableWidgetTrizClients.setColumnCount(0)
        self.tableWidgetTrizClients.setRowCount(0)
        self.tableWidgetTrizClients.horizontalHeader().setStretchLastSection(True)
        self.tableWidgetTrizClients.verticalHeader().setVisible(False)
        self.verticalLayout.addWidget(self.tableWidgetTrizClients)
        self.frame_2 = QtWidgets.QFrame(Dialog)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(251, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.buttonAddTrizClient = QtWidgets.QPushButton(self.frame_2)
        self.buttonAddTrizClient.setObjectName("buttonAddTrizClient")
        self.horizontalLayout_2.addWidget(self.buttonAddTrizClient)
        self.verticalLayout.addWidget(self.frame_2)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Triz Clients"))
        self.label.setText(_translate("Dialog", "Triz Clients"))
        self.editSearchTrizClient.setPlaceholderText(_translate("Dialog", "Recherche un client TRIZ"))
        self.buttonSearchTrizClient.setText(_translate("Dialog", "Search"))
        self.buttonAddTrizClient.setText(_translate("Dialog", "Ajouté"))
